function catalog = get_guangzhou_line7_catalog(route_direction, t_sched_up)
%GET_GUANGZHOU_LINE7_CATALOG Return Guangzhou Line 7 segment catalog by direction.

    route_direction = normalize_route_direction(route_direction);
    if nargin < 2 || isempty(t_sched_up)
        t_sched_up = [129, 169, 184, 177, 185, 219, 214, 329];
    else
        t_sched_up = double(t_sched_up(:)');
        if numel(t_sched_up) ~= 8
            error('t_sched_up override must have 8 values.');
        end
    end

    switch route_direction
        case 'up'
            files = { ...
                'Guangzhou_Line7_IS01_0.000-1.120km.mat', ...
                'Guangzhou_Line7_IS02_1.120-3.028km.mat', ...
                'Guangzhou_Line7_IS03_3.028-5.200km.mat', ...
                'Guangzhou_Line7_IS04_5.200-6.842km.mat', ...
                'Guangzhou_Line7_IS05_6.842-8.958km.mat', ...
                'Guangzhou_Line7_IS06_8.958-11.323km.mat', ...
                'Guangzhou_Line7_IS07_11.323-13.729km.mat', ...
                'Guangzhou_Line7_IS08_13.729-17.507km.mat'};
            t_sched = num2cell(t_sched_up);
        case 'down'
            files = { ...
                'Guangzhou_Line7_Down_IS01_0_000-3_778km.mat', ...
                'Guangzhou_Line7_Down_IS02_3_778-6_184km.mat', ...
                'Guangzhou_Line7_Down_IS03_6_184-8_549km.mat', ...
                'Guangzhou_Line7_Down_IS04_8_549-10_665km.mat', ...
                'Guangzhou_Line7_Down_IS05_10_665-12_307km.mat', ...
                'Guangzhou_Line7_Down_IS06_12_307-14_479km.mat', ...
                'Guangzhou_Line7_Down_IS07_14_479-16_387km.mat', ...
                'Guangzhou_Line7_Down_IS08_16_387-17_507km.mat'};
            % Down direction traverses the up-direction sections in reverse order.
            t_sched = num2cell(fliplr(t_sched_up));
        otherwise
            error('Unsupported route_direction: %s', route_direction);
    end

    catalog = struct( ...
        'name', {'IS01','IS02','IS03','IS04','IS05','IS06','IS07','IS08'}, ...
        'file', files, ...
        'T_sched', t_sched, ...
        'direction', repmat({route_direction}, 1, 8));
end

function route_direction = normalize_route_direction(route_direction)
    if nargin < 1 || isempty(route_direction)
        route_direction = 'up';
        return;
    end

    route_direction = lower(strtrim(char(string(route_direction))));
    switch route_direction
        case {'up', 'u'}
            route_direction = 'up';
        case {'down', 'd'}
            route_direction = 'down';
        otherwise
            error('route_direction must be ''up'' or ''down'', got: %s', route_direction);
    end
end